### ISSUE TITLE
Case id changes?

### ISSUE THREAD

**Issue by mstrofbass** [harvard-lil/capstone#1107]
I stored some of the case metadata a couple of weeks ago and now it appears that the ID of some cases have changed. For example, I have the following metadata for case ID 12422945:

```json
{
	"id" : 12422945,
	"url" : "https://api.case.law/v1/cases/12422945/",
	"frontend_url" : "https://cite.case.law/so-3d/232/611/12422945/",
	"name" : "Blake and Courtney FREEMAN, individually and on behalf of their minor children v. FON’S PEST MANAGEMENT, INC. and ABC Insurance Co.",
	"name_abbreviation" : "Freeman v. Fon’s Pest Management, Inc.",
	"decision_date" : "2017-10-02",
	"docket_number" : "2016 CA 0208",
	"first_page" : "611",
	"last_page" : "628",
	"citations" : [
		{
			"type" : "official",
			"cite" : "232 So. 3d 611"
		}
	],
	"volume" : {
		"url" : "https://api.case.law/v1/volumes/32044142600295/",
		"volume_number" : "232"
	},
	"reporter" : {
		"url" : "https://api.case.law/v1/reporters/1025/",
		"full_name" : "Southern Reporter, Third Series"
	},
	"court" : {
		"url" : "https://api.case.law/v1/courts/la-ct-app/",
		"id" : 10118,
		"slug" : "la-ct-app",
		"name" : "Louisiana Court of Appeal",
		"name_abbreviation" : "La. Ct. App."
	},
	"jurisdiction" : {
		"url" : "https://api.case.law/v1/jurisdictions/la/",
		"id" : 10,
		"slug" : "la",
		"name" : "La.",
		"name_long" : "Louisiana",
		"whitelisted" : false
	}
}
```

That case is no longer accessible by the ID or the URLs associated with that ID, but is accessible by the citation url without the ID. Instead, it appears that the ID has changed. Searching the site gives me this:

```json
{
            "id": 12422940,
            "url": "https://api.case.law/v1/cases/12422940/",
            "frontend_url": "https://cite.case.law/so-3d/232/611/12422940/",
            "name": "Blake and Courtney FREEMAN, individually and on behalf of their minor children v. FON’S PEST MANAGEMENT, INC. and ABC Insurance Co.",
            "name_abbreviation": "Freeman v. Fon’s Pest Management, Inc.",
            "decision_date": "2017-10-02",
            "docket_number": "2016 CA 0208",
            "first_page": "611",
            "last_page": "628",
            "citations": [
                {
                    "type": "official",
                    "cite": "232 So. 3d 611"
                }
            ],
            "volume": {
                "url": "https://api.case.law/v1/volumes/32044142600295/",
                "volume_number": "232"
            },
            "reporter": {
                "url": "https://api.case.law/v1/reporters/1025/",
                "full_name": "Southern Reporter, Third Series"
            },
            "court": {
                "url": "https://api.case.law/v1/courts/la-ct-app/",
                "id": 10118,
                "slug": "la-ct-app",
                "name": "Louisiana Court of Appeal",
                "name_abbreviation": "La. Ct. App."
            },
            "jurisdiction": {
                "url": "https://api.case.law/v1/jurisdictions/la/",
                "id": 10,
                "slug": "la",
                "name": "La.",
                "name_long": "Louisiana",
                "whitelisted": false
            }
        }
```

I can't find anything in the documentation suggesting that ids can change and it specifically suggests appending the id to the API url to retrieve a specific case, so it seems like this isn't intentional.

I have additionally verified that the same issue exists for case `12291359`, which now has id `12291360`. Further, I have the following IDs that returned 404s but have not verified that they fall under the same category:

12422945
12300624
12300650
12300659
12300672
12300687
12300712
12300728
12300747
12300763
12300778
12300793
12300815
12300850
12300874
12300905
12300926
12300944
12300976
12300993
12301006
12301026
12301045
12301096
12301074
12301116
12301133
12301156
12301181
12301203

**Comment by jcushman** [comment]
Hi, @mstrofbass. I haven't confirmed yet for the other examples, but regarding 12422940/12422945 the cause was this: we recently discovered that, due to a missing `unique` index on our database, about 22,000 cases were duplicated during ingest. We deleted the duplicates, and that data update was published today. Prior to today, both 12422940 and 12422945 were returning separate copies of the same case.

Sorry for the confusion! We can run a report to get the full mapping of deleted-duplicates to single preserved copies, but it might be a few days based on folks schedules here.

**Comment by mlissner** [comment]
@mstrofbass can confirm, but unless I'm mistaken, we're only concerned with where these items intersect with the URLs on cite.case.law. In other words, it only *really* matters to us *at this point*, if this was happening to a case with an ambiguous citation *and* a duplicate ID.

**Comment by mstrofbass** [comment]
> Sorry for the confusion! We can run a report to get the full mapping of deleted-duplicates to single preserved copies, but it might be a few days based on folks schedules here.

In hindsight, this is pretty much the only thing that makes sense...I didn't even think to look up what was in the database for the id I was finding on the site.

Coming from an API consumer point of view, I think it would be better to return a [301 response code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) with the other id/uri. That may have been considered and is probably an unnecessary amount of work at this point, but I just wanted to mention it in case it either wasn't considered or things like this start popping up regularly. 

> In other words, it only _really_ matters to us _at this point_, if this was happening to a case with an ambiguous citation _and_ a duplicate ID.

Yeah, this doesn't really cause any actual issues, just something that wasn't expected and worth finding out what was going on. I don't think that report would be necessary at this point, @jcushman. Even in the situation @mlissner describes, there would be enough other information to link them together.

Thanks again for your quick response and explanation!

**Comment by jcushman** [comment]
Looking into this further, there are two separate issues that occurred -- we'll prevent both in the future.

The first thing is as mentioned above -- cases where the same precise data was ingested under two or three different IDs, and the dupes were later deleted. We put a unique index on the table to prevent that.

The second issue was because our vendor reprocessed the scanned images for a minority of our volumes and uploaded new versions of the extracted cases for existing volumes. This resulted in modifying the consecutive vendor IDs for a number of cases, and thus modifying our IDs as well.

Specifically, if the vendor found one case more or less during reprocessing, then every case in the volume after that difference would come in with an ID that previously belonged to a different case. For example, if the 99th case was skipped during the second round of processing, then "<volumeID>_0100" would become "<volumeID>_0099", "<volumeID>_0101" would become "<volumeID>_0100", and so on. We treated these vendor ID changes as metadata corrections during the second ingest, thus changing the contents of those renumbered cases. In the future if we have to reingest a volume (not currently anticipated) we'll figure out a smarter strategy for handling vendor ID changes.

I compared all of the changed IDs in our 7/31 data release. These are the total counts:

* Deleted duplicate cases: 18,141
* New cases (these probably represent actual volumes that weren't included in the previous release): 27,558
* Cases with same IDs and similar but corrected/modified names (these represent metadata corrections [or new errors] from reingesting volumes): 1,640
* Cases with same IDs but dissimilar names (these represent cases renumbered during reprocessing): 4,878

A spreadsheet for each category is included in this zip in case helpful:

[case_id_changes.zip](https://github.com/harvard-lil/capstone/files/3494126/case_id_changes.zip)
