### ISSUE TITLE
Partial dates shown as full dates in front end

### ISSUE THREAD

**Issue by mlissner** [harvard-lil/capstone#1300]
Perhaps a small issue, but when you look at this case in the front end:

https://cite.case.law/bta/29/702/

It shows a date of Jan 1, 1934. But in the JSON data:

https://api.case.law/v1/cases/6075903/

It shows a date of 1934. 

I don't think approximating the date this way should be done without some sort of explanatory note. Probably the best solution is to just show '1934' like it shows in the case itself (I assume). Of course, that's annoying if you're storing dates in your DB as date objects (like we are).

I think our solution is to split the date in the DB (putting June 15, 1934 in the DB instead of the floor value, Jan 1), and to then have a flag on the front end that says it's approximate. I think we wound up there because we also sometimes get cases that just say they were part of the "Spring term" or whatever, so that handles that issue pretty well too. 

If you want to dig into our code, I'd start with a grep for `is_date_approximate`. I think that'd turn up the relevant bits and pieces.

**Comment by jcushman** [comment]
Sorry I missed this earlier, but just stumbled across it -- nice catch!

Our db has `decision_date_original` as a string like `1934`, `1934-01`, or `1934-01-01`, as well as `decision_date` as an actual date column. So my fix here was to check the length of `decision_date_original` and render just "1934", "Jan. 1934", or "Jan. 1, 1934" based on that.

Having some more experience here I'm not 100% sure if the parsed `decision_date` field in the DB is actually helping us at all. You can still do sorting and indexing based just on the string value (in fact sorting on the string automatically gives partial dates an unambiguous spot in the sort order), and not having a real date field stops you from ever using an over-precise date without thinking about it, or having to add special cases for non-existent dates like Feb. 29, 1901. I think if we dropped `decision_date` entirely we'd just need a couple of formatting helpers and otherwise wouldn't miss it.
