### ISSUE TITLE
Search preview doesn't work for two-word phrases

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1435]
E.g. a search for `library trustees` shows previews, but `"library trustees"` doesn't:

https://case.law/search/#/cases?page=1&search=%22library%20trustees%22

**Comment by kilbergr** [comment]
This is only an issue if the quoted phrase is in the body of the text. The material in the headmatter (source field) returns appropriately, the material in the nested text (opinion) does not. It's also working fine for single quotes, it's just double quotes that don't work.

**Comment by kilbergr** [comment]
OK so weirder still...
It's only CERTAIN two-word double quoted phrases that don't work.
Doesn't work: 
"Tailoring Company"
"National Tailoring Company"
"Tailoring Company upon"
Does work (i.e returns text and header matches):
"Scott was plaintiff and National Tailoring Company"
"and National Tailoring Company"
"Scott was plaintiff"
"plaintiff and"
"Tailoring" (although this is not a perfect search of "tailoring"--includes derivations. I believe that's intentional).
