### ISSUE TITLE
Strange border on sidebar

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#1466]
Attempting to hunt down origins, currently remains mysterious

<img width="1138" alt="Screen Shot 2020-05-12 at 11 03 08 AM" src="https://user-images.githubusercontent.com/1494102/81712037-34a1e900-9442-11ea-9bc5-10be25e4df73.png">

**Comment by rebeccacremona** [comment]
I think this is because of the [`overflow: scroll`](https://github.com/harvard-lil/capstone/blob/86e4ed77c143c65d9b7c0e5489838dcad68b5527/capstone/static/css/scss/_page-structure.scss#L269); toggling to `overflow: auto` in dev tools removes the frame and seems to behave correctly at all zooms... I _think_ `auto` is correct here, but am not making a PR because I'm just not that familiar with this design.
