### ISSUE TITLE
Case Number Schema

### ISSUE THREAD

**Issue by c4lliope** [harvard-lil/capstone#1631]
A: https://cite.case.law/ne3d/62/472/12140247/ (62 N.E.3d 472) - 2016
B: https://cite.case.law/ne3d/80/179/12357060/ (80 N.E.3d 179, 62 N.E.3d 472) - 2017
C: https://cite.case.law/ne3d/84/1179/ (84 N.E.3d 1179) - 2017

(Note citations; `C cites A` and `C cites B`)

The case numbers in these three examples are curious to me; can you explain?
* why do B and A share a case number?
* Is `179` -> `1179` significant or an incredible coincidence?
* Why doesn't A's URL display case B, since there is a case number collision?
* Why do A and B have an extra URL segment (`/...`) that C does not?

One more; A and C's pages also display serial numbers;
`No. 27A04-1511-MI-1976` and `No. 27S04-1702-MI-70`.
Any significance?

I'm sure some of this varies court-to-court, or by reporter, but any large-scale trends in the data would be really nice to learn. Much obliged!

**Comment by jcushman** [comment]
Thanks for this report! It looks like what happened here is case B has an incorrectly extracted citation -- that case should only have the citation `80 N.E.3d 179` and not `62 N.E.3d 472`. It makes no sense for a case to have parallel citations from two volumes of the same reporter (`80 N.E.3d` and `62 N.E.3d`), so that's pretty much always going to be an error. There are a bunch of other cases with the same error in [that volume]( https://cite.case.law/ne3d/80/).

I'm flagging this issue for data cleanup. We should run a query for cases that have parallel cites from the same reporter, see how many there are, and hopefully apply an automated fix.

> Why doesn't A's URL display case B, since there is a case number collision?
> Why do A and B have an extra URL segment (/...) that C does not?

The disambiguation URL is https://cite.case.law/ne3d/62/472/ ; we add the case ID to the URL when necessary to disambiguate two cases with the same cite.

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
