### ISSUE TITLE
Nominative Case Citations

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#298]
In many cases that come from nominative volumes, the citation format is wrong.

**Comment by ericnystrom** [comment]
I presume this issue originally pertains to those citations that are wrong because they continue to incorporate some part of the nominative form, such as "2 U.S. (Dall.) 401" which should simply be 2 U.S. 401.

However, in going through the U.S. Supreme Court cases, I noted two volumes that were originally nominative, where the citation was mangled in conversion to the US Reports version for all cases. In both instances, the field "volume->volume_number" was the correct one, it was the "citations->[0]->cite" field that was incorrect.

US Reports vol. 68 cites are incorrectly listed as "1 U.S." (nominative: 1 Peters); US Reports vol. 72 is listed as "5 U.S." (nominative: 5 Wallace).

Thank you!

**Comment by kilbergr** [comment]
Fixed-ish.
