### ISSUE TITLE
Add Regional Citations and Pagination Markers

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#345]

**Comment by jcushman** [comment]
A little more documentation of this bug, particularly for non-lawyers and H2O purposes:

Many cases have multiple citations, because the same case was printed in multiple books. It is common to have an official citation and a regional citation for the same case, both of which are widely used. For example, the Mass. case of Goodridge v. Department of Public Health is cited as 440 Mass. 309 (volume 440 of the Mass. reporter) and as 798 N.E.2d 941 (volume 798 of the North East 2d regional reporter). Typically the first would be used to cite to the case inside Massachusetts and the second outside.

The way this gets handled in legal databases is the case shows both citations at the top of the page, like "* 440 Mass. 309, ** 798 N.E.2d 941", and the text includes inline pagination markers for both, like `*441, *442, *443` and `**942, **943, **944`. This allows citations to a particular page to work, like "440 Mass. 309, 315" or "798 N.E.2d 941, 947".

We tried to only scan the "official" version of each case, so we're missing the regional citations for most cases. (The exceptions being where the regional reporter was the official reporter, or where the official reporter was a reprint that included the regional citations.) This means we can't take a citation like "798 N.E.2d 941, 947" and use it to jump to the appropriate place in [our copy](https://cite.case.law/mass/440/309/) of Goodridge, or match it to Goodridge at all.

We do have totally unprocessed OCR for some regional volumes (the ones which include some official cases), so it might be possible to reconstruct some regional cites and pagination via text matching. Other databases like Fastcase and CourtListener have some of this data as well, and there's been some interest in building a big shared lookup table of all of the citations everyone has for every case, which would also help with this.
