### ISSUE TITLE
Replace blockquotes with regular quotes in text-only format

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#395]
When we convert casebody xml to plain text, replace block quotes with something that indicates the text is a quote.

**Comment by ChefAndy** [comment]
https://cite.case.law/f2d/954/23/

From the API: 

[...]`The Third Circuit put it well:\nGiving supplemental instructions to the jury is usually a delicate and sensitive task requiring the exercise of judgment and skill. The task [is] more delicate when the principal charge is oral and the supplemental instructions are in writing because of the risk of accentuating a segment of the charge by reducing it to writing.\nBeardshall v. Minuteman Press Int’l, Inc.`[...]

<img width="779" alt="Screen Shot 2021-09-13 at 1 31 13 PM" src="https://user-images.githubusercontent.com/1882536/133130069-21feab9e-b12d-42ad-a7c5-7c19d6d057b6.png">

**Comment by kilbergr** [comment]
Formatting issue: in the text extracted from the html, the block quote tag is removed so there's no indication of a block quote (it also lacks the `"` marker). This could confused NLP tools/researchers. If we were to add this, we'd have to be careful of nested quotes.
