### ISSUE TITLE
Update metadata on tribal court cases

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#592]
Thanks to Anne Lucke at the Native American Rights Fund for input. Any errors in the following writeup are mine. :)

So, each tribe has its own independent legal jurisdiction, analogous to a state jurisdiction. To do this right we ought to label cases from the Navajo Nation Supreme Court as part of a "Navajo Nation" jurisdiction, in the same way we label cases from the Massachusetts Supreme Judicial Court as part of the "Massachusetts" jurisdiction.

But we don't have the data for that yet. To do it in practice, we'll need to correctly map back from our list of roughly 50 tribal courts (like "White Earth Band of Chippewa Tribal Court") to the correct tribal jurisdiction. The answer isn't obvious for all of the courts and will need double-checking by knowledgeable people. (Anne mentioned that [Jill Tompkins](https://lawweb.colorado.edu/profiles/profileBasic.jsp?id=58) is one expert.)

In the meantime, a workable compromise is to mark our cases with a plural jurisdiction like "Tribal Jurisdictions", so we're making clear that they're from different tribal jurisdictions not yet specified.

**Comment by kilbergr** [comment]
Add new jurisdictions and alter display since adding these new jurisdictions significantly increases the number of jurisdictions and divides some current logical groupings. We'd have to evaluate how to do that and create a design and implement it for the tribal courts specifically. There's a spreadsheet with these mappings...somewhere.
