### ISSUE TITLE
JSON ingesting of data to capstone

### ISSUE THREAD

**Issue by gryftir** [harvard-lil/capstone#657]
while I expect that the scope of this project is primarily internal users so perhaps this is a non starter, currently there is no ingest function that supports passing along the JSON representation of a case taken from the API and creating a duplicate of the database entry of that representation.

**Comment by jcushman** [comment]
Hi! You're right that currently we don't see many likely users for that feature, and it's also a little tricky because the JSON representation doesn't include all of our internal fields. If there's a usecase we're missing for importing JSON back into this project, we're definitely up for talking about how to support it.

Alternatively I wonder if this request hints at some other features that would be more useful? Like if what you really want is a relational version of the bulk data to run SQL against, I could imagine exporting a sqlite version of our data.

**Comment by ChefAndy** [comment]
I don't think having this issue open indefinitely is going to move this forward, and I don't know that improvements in this vein will come as JSON ingest. I think we should create some docs with more information for external developers and if we think we can create some improvements for that experience, create issues specific to whatever we design. I'll make an issue for more coherent dev documentation, and link to it here so the chain isn't broken.
