### ISSUE TITLE
Page Numbers are Wrong

### ISSUE THREAD

**Issue by johnhungerford** [harvard-lil/capstone#758]
I've noticed the page numbers recorded in the pgmap attribute of the xml formats do not match up with the reporter page numbers for the Supreme Court cases I have examined.

(see Hollingsworth v. Perry, 3639179, and Citizens United v. Federal Exchange Committee, 3639027)

**Comment by jcushman** [comment]
Hi @johnhungerford! The pgmap values you're seeing don't refer to the page labels printed within the book, but rather to the image count in our scanners. You can get from one to the other using the XML.

Here's [Hollingsworth](https://api.case.law/v1/cases/3639179/?format=xml&full_case=true), for example:

```
<casebody xmlns="http://nrs.harvard.edu/urn-3:HLS.Libr.US_Case_Law.Schema.Case_Body:v1" lastpage="208" firstpage="183">
<docketnumber id="A--" pgmap="345">No. 09A648.</docketnumber>

...

<structMap TYPE="physical">
<div TYPE="volume">
<div ORDER="345" ORDERLABEL="183" TYPE="page">
```

`pgmap="345"` indicates that the element appears on the 345th page image we scanned for that volume. If you look under structmap, you can see that the label for that page is "183", which is the first page of the case as labeled by the court. This layer of indirection is necessary because page numbers supplied by courts aren't guaranteed to be unique within a volume, or to be numbers ...
