### ISSUE TITLE
US Reports (US Supreme Court) vol. 44 missing

### ISSUE THREAD

**Issue by ericnystrom** [harvard-lil/capstone#801]
Hello! After going very carefully through the US Supreme Court cases, volume 44 of US Reports (which was originally 3 Howard) is entirely missing from the dataset.  I am using the United States jurisdiction bulk download dated 20181204.

Thank you!

**Comment by jcushman** [comment]
Hi, Eric! This issue relates to #298 (thanks for your feedback on that one as well). In addition to mangled nominative cites, volume 44 has a metadata error marking it as jurisdiction "NY" instead of "US". You can see some of those cases in this query for the "US (Howard)" reporter:

https://beta-api.capapi.org/v1/cases/?reporter=1035

We have some data cleaning spreadsheets in progress that will catch issues like this en masse, but no ETA on getting them applied to the dataset yet. Thanks for documenting this in the meantime.

**Comment by jcushman** [comment]
Looks like a metadata pass fixed this.
