### ISSUE TITLE
Have docker serve node too

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#837]
Currently it's just starting the python server

**Comment by jcushman** [comment]
A downside of running `npm run serve` by default is you then have to manually run `npm run build` or otherwise delete the files it creates, which isn't helpful if you're not doing frontend work. Not sure what a good approach is here -- maybe document a good opt-in way to run `npm run serve` in Docker, or run it by default but have it clean up after itself, or figure out a way to not have it step on the source-controlled files in the first place?

**Comment by jcushman** [comment]
We now have `fab run_frontend`.
